AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyPureLogicFunction:
    Type: AWS::Serverless::Function

    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12

      Architectures:
        - x86_64

      MemorySize: 256
      Timeout: 300

      CodeUri: my-lambda/

      Events:
        MyAsk:
          Type: Api
          Properties:
            Path: /ask-question
            Method: post

      Policies:
        - Statement:

            # Bedrock Foundation Model Permission
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                - arn:aws:bedrock:us-east-1::foundation-model/*

            # Bedrock Inference Profile Permission
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/*

            # CloudWatch Logs Permission
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*

Outputs:
  MyApiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ask-question/"